---
logging:
  level:
    root: info

server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/pdf_platform
    username: dbadmin
    password: XXXXXXXXXXXXXXXXXXX
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      indent_output: true
  jpa:
    generate-ddl: true
---
spring:
  datasource:
    url: jdbc:sqlserver://mssql-2019:11433;databaseName=pdf_platform
    username: sa
    password: MSSQLServer@2019
  config:
    activate:
      on-profile: docker
---
spring:
  datasource:
    url: jdbc:sqlserver://localhost:31433;databaseName=pdf_platform
    username: sa
    password: MSSQLServer@2019
  config:
    activate:
      on-profile: k8s