---
logging:
  level:
    root: info

server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/pdf_platform
    username: dbadmin
    password: XXXXXXXXXXXXXXXXXXX
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      indent_output: true
  jpa:
    generate-ddl: true
---
spring:
  datasource:
    url: jdbc:postgresql://pdf_platform_db:5432/pdf_platform
  config:
    activate:
      on-profile: docker