import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val jackson_core: String = "com.fasterxml.jackson.core:jackson-core:_"

    const val guava: String = "com.google.guava:guava:_"

    const val graphiql_spring_boot_starter: String =
            "com.graphql-java-kickstart:graphiql-spring-boot-starter:_"

    const val graphql_spring_boot_starter: String =
            "com.graphql-java-kickstart:graphql-spring-boot-starter:_"

    const val mssql_jdbc: String = "com.microsoft.sqlserver:mssql-jdbc:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val reactor_test: String = "io.projectreactor:reactor-test"

    const val io_spring_dependency_management_gradle_plugin: String =
            "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:_"

    const val postgresql: String = "org.postgresql:postgresql:_"

    const val org_springframework_boot_gradle_plugin: String =
            "org.springframework.boot:org.springframework.boot.gradle.plugin:_"

    const val spring_boot_devtools: String = "org.springframework.boot:spring-boot-devtools:_"

    const val spring_boot_starter_data_jpa: String =
            "org.springframework.boot:spring-boot-starter-data-jpa"

    const val spring_boot_starter_test: String =
            "org.springframework.boot:spring-boot-starter-test:_"

    const val spring_boot_starter_web: String = "org.springframework.boot:spring-boot-starter-web:_"
}
